blank_issues_enabled: true
contact_links:
  - name: Contribution Details
    url: https://github.com/martin-temp/task-app-binary-search/blob/main/CONTRIBUTING.md
    about: Before opening a new issue, please make sure to read CONTRIBUTING.md
